export interface Business {
  id: string;
  name: string;
  tagline: string;
  description: string;
  category: BusinessCategory;
  isVerified: boolean;
  isFeatured: boolean;
  location: {
    city: string;
    state: string;
    zipCode: string;
    country: string;
  };
  tags: BusinessTag[];
  imageUrl?: string;
}

export interface Category {
  id: string;
  name: string;
  slug: string;
  description: string;
  iconName: string;
}

export enum BusinessCategory {
  ARTS_CRAFTS_PARTY_SUPPLIES = 'Arts, Crafts & Party Supplies',
  AUTO_TIRES_INDUSTRIAL = 'Auto, Tires & Industrial',
  BABY = 'Baby',
  BEAUTY_COSMETICS = 'Beauty & Cosmetics',
  BEDDING_LINENS = 'Bedding & Linens',
  CELL_PHONES_ACCESSORIES = 'Cell Phones & Accessories',
  CHAMBER = 'Chamber',
  CHILD_CARE_DAY_CARE = 'Child Care & Day Care',
  CLEANING_SUPPLIES = 'Cleaning Supplies',
  CLOTHING_SHOES_ACCESSORIES = 'Clothing, Shoes & Accessories',
  CONTENT_CREATION = 'Content Creation',
  CRAFT_KITS_DIY_PROJECTS = 'Craft Kits & DIY Projects',
  DIGITAL_PRODUCTS = 'Digital Products',
  DIRECTORY = 'Directory',
  EDUCATION = 'Education',
  ELECTRONICS_AUDIO = 'Electronics & Audio',
  EVENT_TICKETS_EXPERIENCES = 'Event Tickets & Experiences',
  EXERCISE_FITNESS = 'Exercise & Fitness',
  FILM_PRODUCTION = 'Film & Production',
  FINANCE_PAYMENTS = 'Finance & Payments',
  FINANCIAL_INSTITUTION = 'Financial Institution',
  FOOD_BEVERAGE = 'Food & Beverage',
  FURNITURE_APPLIANCES = 'Furniture & Appliances',
  GARDENING_TOOLS_SUPPLIES = 'Gardening Tools & Supplies',
  GIFTS_GREETING_CARDS = 'Gifts & Greeting Cards',
  GROCERY = 'Grocery',
  HEALTH_WELLNESS = 'Health & Wellness',
  HOME_IMPROVEMENTS_DECOR = 'Home Improvements & Decor',
  HOME_SECURITY_SMART_DEVICES = 'Home Security & Smart Devices',
  HOUSEHOLD_ESSENTIALS = 'Household Essentials',
  INFLUENCER = 'Influencer',
  JEWELRY_WATCHES = 'Jewelry & Watches',
  KITCHENWARE_COOKWARE = 'Kitchenware & Cookware',
  LUGGAGE_BAGS = 'Luggage & Bags',
  MEDICAL_HEALTHCARE = 'Medical & Healthcare',
  MERCHANT_SERVICES = 'Merchant Services',
  MISCELLANEOUS = 'Miscellaneous',
  MOBILE_APPS_SOFTWARE_LICENSES = 'Mobile Apps & Software Licenses',
  MUSIC_MOVIES_BOOKS = 'Music, Movies & Books',
  NONPROFIT = 'Nonprofit',
  OFFICE_FURNITURE = 'Office Furniture',
  OFFICE_SUPPLIES = 'Office Supplies',
  OUTDOOR_CAMPING_EQUIPMENT = 'Outdoor & Camping Equipment',
  PATIO_GARDEN = 'Patio & Garden',
  PERSONAL_CARE = 'Personal Care',
  PETS = 'Pets',
  PHARMACY_HEALTH_WELLNESS = 'Pharmacy, Health & Wellness',
  PROFESSIONAL_SERVICES = 'Professional Services',
  REAL_ESTATE = 'Real Estate',
  RELIGIOUS_SPIRITUAL = 'Religious & Spiritual',
  RESTAURANTS_BARS_LOUNGE = 'Restaurants, Bars & Lounge',
  SEASONAL_HOLIDAY_ITEMS = 'Seasonal & Holiday Items',
  SPORTS_OUTDOORS = 'Sports & Outdoors',
  STATIONERY_OFFICE_SUPPLIES = 'Stationery & Office Supplies',
  SUBSCRIPTION_BOXES = 'Subscription Boxes',
  TECHNOLOGY = 'Technology',
  TOOLS_HARDWARE = 'Tools & Hardware',
  TOYS_GAMES = 'Toys & Games',
  TRADE_ASSOCIATION = 'Trade Association',
  TRAVEL_TRANSPORTATION = 'Travel & Transportation',
  VINTAGE_COLLECTIBLES = 'Vintage & Collectibles',
  WINE_SPIRITS_LIQUOR = 'Wine, Spirits & Liquor'
}

export enum BusinessTag {
  ART_SUPPLIES = 'Art Supplies',
  PARTY_SUPPLIES = 'Party Supplies',
  CUSTOM_INVITATIONS = 'Custom Invitations',
  KIDS_CRAFTS = 'Kids Crafts',
  SEASONAL_CRAFTS = 'Seasonal Crafts',
  PAINT_BRUSHES = 'Paint Brushes',
  CANVAS_BOARDS = 'Canvas Boards',
  GLUE_GLITTER = 'Glue & Glitter',
  DIY_KITS = 'DIY Kits',
  CRAFT_CLASSES = 'Craft Classes',
  CAR_PARTS = 'Car Parts',
  AUTO_ACCESSORIES = 'Auto Accessories',
  MOTOR_OIL = 'Motor Oil',
  TIRE_SERVICES = 'Tire Services',
  CAR_AUDIO = 'Car Audio',
  CAR_WASH_KITS = 'Car Wash Kits',
  GARAGE_EQUIPMENT = 'Garage Equipment',
  REPAIR_TOOLS = 'Repair Tools',
  JUMP_STARTERS = 'Jump Starters',
  LED_HEADLIGHTS = 'LED Headlights',
  BABY_CLOTHES = 'Baby Clothes',
  STROLLERS_CAR_SEATS = 'Strollers & Car Seats',
  DIAPERS_WIPES = 'Diapers & Wipes',
  NURSERY_DECOR = 'Nursery Decor',
  BABY_MONITORS = 'Baby Monitors',
  FEEDING_SETS = 'Feeding Sets',
  TEETHING_TOYS = 'Teething Toys',
  CRIBS_BASSINETS = 'Cribs & Bassinets',
  MATERNITY_WEAR = 'Maternity Wear',
  BABY_BOOKS = 'Baby Books',
  SKINCARE_SETS = 'Skincare Sets',
  LIPSTICKS = 'Lipsticks',
  FRAGRANCES_PERFUME = 'Fragrances & Perfume',
  HAIR_STYLING_TOOLS = 'Hair Styling Tools',
  NAIL_POLISH = 'Nail Polish',
  FACIAL_MASKS = 'Facial Masks',
  MAKEUP_BRUSHES = 'Makeup Brushes',
  ORGANIC_BEAUTY = 'Organic Beauty',
  BARBER_KITS = 'Barber Kits',
  EYEBROW_KITS = 'Eyebrow Kits',
  WOMENS_FASHION = "Women's Fashion",
  MENSWEAR = 'Menswear',
  SNEAKERS = 'Sneakers',
  FASHION_ACCESSORIES = 'Fashion Accessories',
  DESIGNER_BAGS = 'Designer Bags',
  JEWELRY_SETS = 'Jewelry Sets',
  PLUS_SIZE_WEAR = 'Plus Size Wear',
  HATS_SCARVES = 'Hats & Scarves',
  DENIM_WEAR = 'Denim Wear',
  KIDS_FASHION = 'Kids Fashion',
  LAPTOPS_COMPUTERS = 'Laptops & Computers',
  SMARTPHONES = 'Smartphones',
  BLUETOOTH_SPEAKERS = 'Bluetooth Speakers',
  TV_MONITORS = 'TV & Monitors',
  HOME_SECURITY_CAMS = 'Home Security Cameras',
  VIDEO_DOORBELLS = 'Video Doorbells',
  GAMING_CONSOLES = 'Gaming Consoles',
  HEADPHONES = 'Headphones',
  CHARGING_STATIONS = 'Charging Stations',
  TECH_ACCESSORIES = 'Tech Accessories',
  DUMBBELLS = 'Dumbbells',
  YOGA_MATS = 'Yoga Mats',
  RESISTANCE_BANDS = 'Resistance Bands',
  STATIONARY_BIKES = 'Stationary Bikes',
  PROTEIN_SHAKES = 'Protein Shakes',
  FOAM_ROLLERS = 'Foam Rollers',
  HOME_GYMS = 'Home Gyms',
  FITNESS_TIMERS = 'Fitness Timers',
  GYM_CLOTHES = 'Gym Clothes',
  BODYWEIGHT_BARS = 'Bodyweight Bars',
  GOURMET_SNACKS = 'Gourmet Snacks',
  MEAL_KITS = 'Meal Kits',
  ETHNIC_FOODS = 'Ethnic Foods',
  COFFEE_BLENDS = 'Coffee Blends',
  VEGAN_TREATS = 'Vegan Treats',
  COOKING_INGREDIENTS = 'Cooking Ingredients',
  ARTISAN_BREAD = 'Artisan Bread',
  SPICES_RUBS = 'Spices & Rubs',
  SHELF_STABLE_MEALS = 'Shelf Stable Meals',
  BEVERAGE_VARIETY = 'Beverage Variety',
  SOFAS = 'Sofas',
  DINING_TABLES = 'Dining Tables',
  MICROWAVES = 'Microwaves',
  REFRIGERATORS = 'Refrigerators',
  BED_FRAMES = 'Bed Frames',
  CLOSET_ORGANIZERS = 'Closet Organizers',
  TV_STANDS = 'TV Stands',
  WASHER_DRYER_SETS = 'Washer & Dryer Sets',
  OTTOMANS = 'Ottomans',
  FUTON_COUCHES = 'Futon Couches',
  ORGANIC_VEGGIES = 'Organic Veggies',
  PANTRY_ITEMS = 'Pantry Items',
  FROZEN_GOODS = 'Frozen Goods',
  DELI_ITEMS = 'Deli Items',
  DAIRY_EGGS = 'Dairy & Eggs',
  SNACK_PACKS = 'Snack Packs',
  BAKING_GOODS = 'Baking Goods',
  GROCERY_BUNDLES = 'Grocery Bundles',
  CEREAL_BOXES = 'Cereal Boxes',
  GRAINS_LEGUMES = 'Grains & Legumes',
  WALL_PAINT = 'Wall Paint',
  LIGHT_FIXTURES = 'Light Fixtures',
  WALL_ART = 'Wall Art',
  FLOOR_TILES = 'Floor Tiles',
  TOOLKITS = 'Toolkits',
  FAUCETS_FIXTURES = 'Faucets & Fixtures',
  KITCHEN_SINKS = 'Kitchen Sinks',
  WINDOW_BLINDS = 'Window Blinds',
  HOME_DECOR_BUNDLES = 'Home Decor Bundles',
  REMODELING_SERVICES = 'Remodeling Services',
  PAPER_TOWELS = 'Paper Towels',
  TOILET_PAPER = 'Toilet Paper',
  CLEANING_SPRAYS = 'Cleaning Sprays',
  LAUNDRY_DETERGENTS = 'Laundry Detergents',
  MOPS_BROOMS = 'Mops & Brooms',
  DISINFECTANT_WIPES = 'Disinfectant Wipes',
  TRASH_BAGS = 'Trash Bags',
  AIR_FRESHENERS = 'Air Fresheners',
  DISH_SOAP = 'Dish Soap',
  BATHROOM_CLEANERS = 'Bathroom Cleaners',
  WEDDING_RINGS = 'Wedding Rings',
  LUXURY_WATCHES = 'Luxury Watches',
  PENDANTS = 'Pendants',
  BRACELETS = 'Bracelets',
  CUSTOM_JEWELRY = 'Custom Jewelry',
  EARRINGS = 'Earrings',
  ENGAGEMENT_RINGS = 'Engagement Rings',
  GEMS = 'Gems',
  JEWELRY_STORAGE = 'Jewelry Storage',
  WATCH_BATTERIES = 'Watch Batteries',
  MUSICAL_INSTRUMENTS = 'Musical Instruments',
  RECORD_VINYL = 'Record Vinyl',
  AUDIOBOOKS = 'Audiobooks',
  BOOK_CLUB = 'Book Club',
  PIANO_LESSONS = 'Piano Lessons',
  GUITAR_STRAPS = 'Guitar Straps',
  MP3_DOWNLOADS = 'MP3 Downloads',
  MOVIE_NIGHT_BUNDLES = 'Movie Night Bundles',
  CD_DVD = 'CD & DVD',
  BLU_RAY_COLLECTIONS = 'Blu-ray Collections',
  OUTDOOR_CHAIRS = 'Outdoor Chairs',
  GARDEN_LIGHTS = 'Garden Lights',
  GRILLS_BBQ = 'Grills & BBQ',
  PLANTERS_POTS = 'Planters & Pots',
  PATIO_SETS = 'Patio Sets',
  SHADE_UMBRELLAS = 'Shade Umbrellas',
  OUTDOOR_RUGS = 'Outdoor Rugs',
  DECK_TILES = 'Deck Tiles',
  FIRE_PITS = 'Fire Pits',
  GAZEBO_KITS = 'Gazebo Kits',
  RAZORS_SHAVING = 'Razors & Shaving',
  BODY_WASH = 'Body Wash',
  DEODORANTS = 'Deodorants',
  TOOTHBRUSH_SETS = 'Toothbrush Sets',
  HAIR_REMOVAL_KITS = 'Hair Removal Kits',
  COTTON_SWABS = 'Cotton Swabs',
  FACE_ROLLERS = 'Face Rollers',
  SUNSCREEN_LOTIONS = 'Sunscreen Lotions',
  NAIL_TOOLS = 'Nail Tools',
  TOWEL_SETS = 'Towel Sets',
  PET_FOOD = 'Pet Food',
  DOG_CLOTHES = 'Dog Clothes',
  CAT_TREES = 'Cat Trees',
  PET_BEDS = 'Pet Beds',
  COLLARS_LEASHES = 'Collars & Leashes',
  AQUARIUM_KITS = 'Aquarium Kits',
  GROOMING_SUPPLIES = 'Grooming Supplies',
  PET_TOYS = 'Pet Toys',
  PET_TREATS = 'Pet Treats',
  LITTER_BOXES = 'Litter Boxes',
  VITAMINS_SUPPLEMENTS = 'Vitamins & Supplements',
  PAIN_RELIEVERS = 'Pain Relievers',
  FIRST_AID_KITS = 'First Aid Kits',
  THERMOMETERS = 'Thermometers',
  PERSONAL_PROTECTION = 'Personal Protection',
  WELLNESS_KITS = 'Wellness Kits',
  BANDAGES = 'Bandages',
  HEATING_PADS = 'Heating Pads',
  SLEEP_AIDS = 'Sleep Aids',
  SANITIZERS = 'Sanitizers',
  CAMPING_GEAR = 'Camping Gear',
  KAYAKS = 'Kayaks',
  HIKING_BOOTS = 'Hiking Boots',
  SPORTSWEAR = 'Sportswear',
  OUTDOOR_TOOLS = 'Outdoor Tools',
  TENNIS_RACKETS = 'Tennis Rackets',
  BIKES_SCOOTERS = 'Bikes & Scooters',
  GOLF_ACCESSORIES = 'Golf Accessories',
  WINTER_SPORTS_GEAR = 'Winter Sports Gear',
  FISHING_EQUIPMENT = 'Fishing Equipment',
  NOTEBOOKS = 'Notebooks',
  PENS_PENCILS = 'Pens & Pencils',
  FOLDERS = 'Folders',
  PRINTER_PAPER = 'Printer Paper',
  FILING_SYSTEMS = 'Filing Systems',
  WHITEBOARDS = 'Whiteboards',
  LABELS_STICKERS = 'Labels & Stickers',
  OFFICE_GADGETS = 'Office Gadgets',
  ENVELOPES = 'Envelopes',
  STATIONERY_SETS = 'Stationery Sets',
  BOARD_GAMES = 'Board Games',
  VIDEO_GAMES = 'Video Games',
  PUZZLES = 'Puzzles',
  DOLLS = 'Dolls',
  RC_TOYS = 'RC Toys',
  BUILDING_BLOCKS = 'Building Blocks',
  KIDS_BOOKS = 'Kids Books',
  OUTDOOR_PLAYSETS = 'Outdoor Playsets',
  SCIENCE_KITS = 'Science Kits',
  TOY_STORAGE = 'Toy Storage',
  LUGGAGE_SETS = 'Luggage Sets',
  CARRY_ONS = 'Carry-ons',
  PACKING_CUBES = 'Packing Cubes',
  TRAVEL_PILLOWS = 'Travel Pillows',
  ADAPTERS_CONVERTERS = 'Adapters & Converters',
  PASSPORT_HOLDERS = 'Passport Holders',
  TRAVEL_BACKPACKS = 'Travel Backpacks',
  TRAVEL_SIZE_TOILETRIES = 'Travel Size Toiletries',
  DUFFEL_BAGS = 'Duffel Bags',
  LUGGAGE_TAGS = 'Luggage Tags'
}

export const BusinessTagLabels: Record<BusinessTag, string> = {
  [BusinessTag.ART_SUPPLIES]: 'Art Supplies',
  [BusinessTag.PARTY_SUPPLIES]: 'Party Supplies',
  [BusinessTag.CUSTOM_INVITATIONS]: 'Custom Invitations',
  [BusinessTag.KIDS_CRAFTS]: 'Kids Crafts',
  [BusinessTag.SEASONAL_CRAFTS]: 'Seasonal Crafts',
  [BusinessTag.PAINT_BRUSHES]: 'Paint Brushes',
  [BusinessTag.CANVAS_BOARDS]: 'Canvas Boards',
  [BusinessTag.GLUE_GLITTER]: 'Glue & Glitter',
  [BusinessTag.DIY_KITS]: 'DIY Kits',
  [BusinessTag.CRAFT_CLASSES]: 'Craft Classes',
  [BusinessTag.CAR_PARTS]: 'Car Parts',
  [BusinessTag.AUTO_ACCESSORIES]: 'Auto Accessories',
  [BusinessTag.MOTOR_OIL]: 'Motor Oil',
  [BusinessTag.TIRE_SERVICES]: 'Tire Services',
  [BusinessTag.CAR_AUDIO]: 'Car Audio',
  [BusinessTag.CAR_WASH_KITS]: 'Car Wash Kits',
  [BusinessTag.GARAGE_EQUIPMENT]: 'Garage Equipment',
  [BusinessTag.REPAIR_TOOLS]: 'Repair Tools',
  [BusinessTag.JUMP_STARTERS]: 'Jump Starters',
  [BusinessTag.LED_HEADLIGHTS]: 'LED Headlights',
  [BusinessTag.BABY_CLOTHES]: 'Baby Clothes',
  [BusinessTag.STROLLERS_CAR_SEATS]: 'Strollers & Car Seats',
  [BusinessTag.DIAPERS_WIPES]: 'Diapers & Wipes',
  [BusinessTag.NURSERY_DECOR]: 'Nursery Decor',
  [BusinessTag.BABY_MONITORS]: 'Baby Monitors',
  [BusinessTag.FEEDING_SETS]: 'Feeding Sets',
  [BusinessTag.TEETHING_TOYS]: 'Teething Toys',
  [BusinessTag.CRIBS_BASSINETS]: 'Cribs & Bassinets',
  [BusinessTag.MATERNITY_WEAR]: 'Maternity Wear',
  [BusinessTag.BABY_BOOKS]: 'Baby Books',
  [BusinessTag.SKINCARE_SETS]: 'Skincare Sets',
  [BusinessTag.LIPSTICKS]: 'Lipsticks',
  [BusinessTag.FRAGRANCES_PERFUME]: 'Fragrances & Perfume',
  [BusinessTag.HAIR_STYLING_TOOLS]: 'Hair Styling Tools',
  [BusinessTag.NAIL_POLISH]: 'Nail Polish',
  [BusinessTag.FACIAL_MASKS]: 'Facial Masks',
  [BusinessTag.MAKEUP_BRUSHES]: 'Makeup Brushes',
  [BusinessTag.ORGANIC_BEAUTY]: 'Organic Beauty',
  [BusinessTag.BARBER_KITS]: 'Barber Kits',
  [BusinessTag.EYEBROW_KITS]: 'Eyebrow Kits',
  [BusinessTag.WOMENS_FASHION]: "Women's Fashion",
  [BusinessTag.MENSWEAR]: 'Menswear',
  [BusinessTag.SNEAKERS]: 'Sneakers',
  [BusinessTag.FASHION_ACCESSORIES]: 'Fashion Accessories',
  [BusinessTag.DESIGNER_BAGS]: 'Designer Bags',
  [BusinessTag.JEWELRY_SETS]: 'Jewelry Sets',
  [BusinessTag.PLUS_SIZE_WEAR]: 'Plus Size Wear',
  [BusinessTag.HATS_SCARVES]: 'Hats & Scarves',
  [BusinessTag.DENIM_WEAR]: 'Denim Wear',
  [BusinessTag.KIDS_FASHION]: 'Kids Fashion',
  [BusinessTag.LAPTOPS_COMPUTERS]: 'Laptops & Computers',
  [BusinessTag.SMARTPHONES]: 'Smartphones',
  [BusinessTag.BLUETOOTH_SPEAKERS]: 'Bluetooth Speakers',
  [BusinessTag.TV_MONITORS]: 'TV & Monitors',
  [BusinessTag.HOME_SECURITY_CAMS]: 'Home Security Cameras',
  [BusinessTag.VIDEO_DOORBELLS]: 'Video Doorbells',
  [BusinessTag.GAMING_CONSOLES]: 'Gaming Consoles',
  [BusinessTag.HEADPHONES]: 'Headphones',
  [BusinessTag.CHARGING_STATIONS]: 'Charging Stations',
  [BusinessTag.TECH_ACCESSORIES]: 'Tech Accessories',
  [BusinessTag.DUMBBELLS]: 'Dumbbells',
  [BusinessTag.YOGA_MATS]: 'Yoga Mats',
  [BusinessTag.RESISTANCE_BANDS]: 'Resistance Bands',
  [BusinessTag.STATIONARY_BIKES]: 'Stationary Bikes',
  [BusinessTag.PROTEIN_SHAKES]: 'Protein Shakes',
  [BusinessTag.FOAM_ROLLERS]: 'Foam Rollers',
  [BusinessTag.HOME_GYMS]: 'Home Gyms',
  [BusinessTag.FITNESS_TIMERS]: 'Fitness Timers',
  [BusinessTag.GYM_CLOTHES]: 'Gym Clothes',
  [BusinessTag.BODYWEIGHT_BARS]: 'Bodyweight Bars',
  [BusinessTag.GOURMET_SNACKS]: 'Gourmet Snacks',
  [BusinessTag.MEAL_KITS]: 'Meal Kits',
  [BusinessTag.ETHNIC_FOODS]: 'Ethnic Foods',
  [BusinessTag.COFFEE_BLENDS]: 'Coffee Blends',
  [BusinessTag.VEGAN_TREATS]: 'Vegan Treats',
  [BusinessTag.COOKING_INGREDIENTS]: 'Cooking Ingredients',
  [BusinessTag.ARTISAN_BREAD]: 'Artisan Bread',
  [BusinessTag.SPICES_RUBS]: 'Spices & Rubs',
  [BusinessTag.SHELF_STABLE_MEALS]: 'Shelf Stable Meals',
  [BusinessTag.BEVERAGE_VARIETY]: 'Beverage Variety',
  [BusinessTag.SOFAS]: 'Sofas',
  [BusinessTag.DINING_TABLES]: 'Dining Tables',
  [BusinessTag.MICROWAVES]: 'Microwaves',
  [BusinessTag.REFRIGERATORS]: 'Refrigerators',
  [BusinessTag.BED_FRAMES]: 'Bed Frames',
  [BusinessTag.CLOSET_ORGANIZERS]: 'Closet Organizers',
  [BusinessTag.TV_STANDS]: 'TV Stands',
  [BusinessTag.WASHER_DRYER_SETS]: 'Washer & Dryer Sets',
  [BusinessTag.OTTOMANS]: 'Ottomans',
  [BusinessTag.FUTON_COUCHES]: 'Futon Couches',
  [BusinessTag.ORGANIC_VEGGIES]: 'Organic Veggies',
  [BusinessTag.PANTRY_ITEMS]: 'Pantry Items',
  [BusinessTag.FROZEN_GOODS]: 'Frozen Goods',
  [BusinessTag.DELI_ITEMS]: 'Deli Items',
  [BusinessTag.DAIRY_EGGS]: 'Dairy & Eggs',
  [BusinessTag.SNACK_PACKS]: 'Snack Packs',
  [BusinessTag.BAKING_GOODS]: 'Baking Goods',
  [BusinessTag.GROCERY_BUNDLES]: 'Grocery Bundles',
  [BusinessTag.CEREAL_BOXES]: 'Cereal Boxes',
  [BusinessTag.GRAINS_LEGUMES]: 'Grains & Legumes',
  [BusinessTag.WALL_PAINT]: 'Wall Paint',
  [BusinessTag.LIGHT_FIXTURES]: 'Light Fixtures',
  [BusinessTag.WALL_ART]: 'Wall Art',
  [BusinessTag.FLOOR_TILES]: 'Floor Tiles',
  [BusinessTag.TOOLKITS]: 'Toolkits',
  [BusinessTag.FAUCETS_FIXTURES]: 'Faucets & Fixtures',
  [BusinessTag.KITCHEN_SINKS]: 'Kitchen Sinks',
  [BusinessTag.WINDOW_BLINDS]: 'Window Blinds',
  [BusinessTag.HOME_DECOR_BUNDLES]: 'Home Decor Bundles',
  [BusinessTag.REMODELING_SERVICES]: 'Remodeling Services',
  [BusinessTag.PAPER_TOWELS]: 'Paper Towels',
  [BusinessTag.TOILET_PAPER]: 'Toilet Paper',
  [BusinessTag.CLEANING_SPRAYS]: 'Cleaning Sprays',
  [BusinessTag.LAUNDRY_DETERGENTS]: 'Laundry Detergents',
  [BusinessTag.MOPS_BROOMS]: 'Mops & Brooms',
  [BusinessTag.DISINFECTANT_WIPES]: 'Disinfectant Wipes',
  [BusinessTag.TRASH_BAGS]: 'Trash Bags',
  [BusinessTag.AIR_FRESHENERS]: 'Air Fresheners',
  [BusinessTag.DISH_SOAP]: 'Dish Soap',
  [BusinessTag.BATHROOM_CLEANERS]: 'Bathroom Cleaners',
  [BusinessTag.WEDDING_RINGS]: 'Wedding Rings',
  [BusinessTag.LUXURY_WATCHES]: 'Luxury Watches',
  [BusinessTag.PENDANTS]: 'Pendants',
  [BusinessTag.BRACELETS]: 'Bracelets',
  [BusinessTag.CUSTOM_JEWELRY]: 'Custom Jewelry',
  [BusinessTag.EARRINGS]: 'Earrings',
  [BusinessTag.ENGAGEMENT_RINGS]: 'Engagement Rings',
  [BusinessTag.GEMS]: 'Gems',
  [BusinessTag.JEWELRY_STORAGE]: 'Jewelry Storage',
  [BusinessTag.WATCH_BATTERIES]: 'Watch Batteries',
  [BusinessTag.MUSICAL_INSTRUMENTS]: 'Musical Instruments',
  [BusinessTag.RECORD_VINYL]: 'Record Vinyl',
  [BusinessTag.AUDIOBOOKS]: 'Audiobooks',
  [BusinessTag.BOOK_CLUB]: 'Book Club',
  [BusinessTag.PIANO_LESSONS]: 'Piano Lessons',
  [BusinessTag.GUITAR_STRAPS]: 'Guitar Straps',
  [BusinessTag.MP3_DOWNLOADS]: 'MP3 Downloads',
  [BusinessTag.MOVIE_NIGHT_BUNDLES]: 'Movie Night Bundles',
  [BusinessTag.CD_DVD]: 'CD & DVD',
  [BusinessTag.BLU_RAY_COLLECTIONS]: 'Blu-ray Collections',
  [BusinessTag.OUTDOOR_CHAIRS]: 'Outdoor Chairs',
  [BusinessTag.GARDEN_LIGHTS]: 'Garden Lights',
  [BusinessTag.GRILLS_BBQ]: 'Grills & BBQ',
  [BusinessTag.PLANTERS_POTS]: 'Planters & Pots',
  [BusinessTag.PATIO_SETS]: 'Patio Sets',
  [BusinessTag.SHADE_UMBRELLAS]: 'Shade Umbrellas',
  [BusinessTag.OUTDOOR_RUGS]: 'Outdoor Rugs',
  [BusinessTag.DECK_TILES]: 'Deck Tiles',
  [BusinessTag.FIRE_PITS]: 'Fire Pits',
  [BusinessTag.GAZEBO_KITS]: 'Gazebo Kits',
  [BusinessTag.RAZORS_SHAVING]: 'Razors & Shaving',
  [BusinessTag.BODY_WASH]: 'Body Wash',
  [BusinessTag.DEODORANTS]: 'Deodorants',
  [BusinessTag.TOOTHBRUSH_SETS]: 'Toothbrush Sets',
  [BusinessTag.HAIR_REMOVAL_KITS]: 'Hair Removal Kits',
  [BusinessTag.COTTON_SWABS]: 'Cotton Swabs',
  [BusinessTag.FACE_ROLLERS]: 'Face Rollers',
  [BusinessTag.SUNSCREEN_LOTIONS]: 'Sunscreen Lotions',
  [BusinessTag.NAIL_TOOLS]: 'Nail Tools',
  [BusinessTag.TOWEL_SETS]: 'Towel Sets',
  [BusinessTag.PET_FOOD]: 'Pet Food',
  [BusinessTag.DOG_CLOTHES]: 'Dog Clothes',
  [BusinessTag.CAT_TREES]: 'Cat Trees',
  [BusinessTag.PET_BEDS]: 'Pet Beds',
  [BusinessTag.COLLARS_LEASHES]: 'Collars & Leashes',
  [BusinessTag.AQUARIUM_KITS]: 'Aquarium Kits',
  [BusinessTag.GROOMING_SUPPLIES]: 'Grooming Supplies',
  [BusinessTag.PET_TOYS]: 'Pet Toys',
  [BusinessTag.PET_TREATS]: 'Pet Treats',
  [BusinessTag.LITTER_BOXES]: 'Litter Boxes',
  [BusinessTag.VITAMINS_SUPPLEMENTS]: 'Vitamins & Supplements',
  [BusinessTag.PAIN_RELIEVERS]: 'Pain Relievers',
  [BusinessTag.FIRST_AID_KITS]: 'First Aid Kits',
  [BusinessTag.THERMOMETERS]: 'Thermometers',
  [BusinessTag.PERSONAL_PROTECTION]: 'Personal Protection',
  [BusinessTag.WELLNESS_KITS]: 'Wellness Kits',
  [BusinessTag.BANDAGES]: 'Bandages',
  [BusinessTag.HEATING_PADS]: 'Heating Pads',
  [BusinessTag.SLEEP_AIDS]: 'Sleep Aids',
  [BusinessTag.SANITIZERS]: 'Sanitizers',
  [BusinessTag.CAMPING_GEAR]: 'Camping Gear',
  [BusinessTag.KAYAKS]: 'Kayaks',
  [BusinessTag.HIKING_BOOTS]: 'Hiking Boots',
  [BusinessTag.SPORTSWEAR]: 'Sportswear',
  [BusinessTag.OUTDOOR_TOOLS]: 'Outdoor Tools',
  [BusinessTag.TENNIS_RACKETS]: 'Tennis Rackets',
  [BusinessTag.BIKES_SCOOTERS]: 'Bikes & Scooters',
  [BusinessTag.GOLF_ACCESSORIES]: 'Golf Accessories',
  [BusinessTag.WINTER_SPORTS_GEAR]: 'Winter Sports Gear',
  [BusinessTag.FISHING_EQUIPMENT]: 'Fishing Equipment',
  [BusinessTag.NOTEBOOKS]: 'Notebooks',
  [BusinessTag.PENS_PENCILS]: 'Pens & Pencils',
  [BusinessTag.FOLDERS]: 'Folders',
  [BusinessTag.PRINTER_PAPER]: 'Printer Paper',
  [BusinessTag.FILING_SYSTEMS]: 'Filing Systems',
  [BusinessTag.WHITEBOARDS]: 'Whiteboards',
  [BusinessTag.LABELS_STICKERS]: 'Labels & Stickers',
  [BusinessTag.OFFICE_GADGETS]: 'Office Gadgets',
  [BusinessTag.ENVELOPES]: 'Envelopes',
  [BusinessTag.STATIONERY_SETS]: 'Stationery Sets',
  [BusinessTag.BOARD_GAMES]: 'Board Games',
  [BusinessTag.VIDEO_GAMES]: 'Video Games',
  [BusinessTag.PUZZLES]: 'Puzzles',
  [BusinessTag.DOLLS]: 'Dolls',
  [BusinessTag.RC_TOYS]: 'RC Toys',
  [BusinessTag.BUILDING_BLOCKS]: 'Building Blocks',
  [BusinessTag.KIDS_BOOKS]: 'Kids Books',
  [BusinessTag.OUTDOOR_PLAYSETS]: 'Outdoor Playsets',
  [BusinessTag.SCIENCE_KITS]: 'Science Kits',
  [BusinessTag.TOY_STORAGE]: 'Toy Storage',
  [BusinessTag.LUGGAGE_SETS]: 'Luggage Sets',
  [BusinessTag.CARRY_ONS]: 'Carry-ons',
  [BusinessTag.PACKING_CUBES]: 'Packing Cubes',
  [BusinessTag.TRAVEL_PILLOWS]: 'Travel Pillows',
  [BusinessTag.ADAPTERS_CONVERTERS]: 'Adapters & Converters',
  [BusinessTag.PASSPORT_HOLDERS]: 'Passport Holders',
  [BusinessTag.TRAVEL_BACKPACKS]: 'Travel Backpacks',
  [BusinessTag.TRAVEL_SIZE_TOILETRIES]: 'Travel Size Toiletries',
  [BusinessTag.DUFFEL_BAGS]: 'Duffel Bags',
  [BusinessTag.LUGGAGE_TAGS]: 'Luggage Tags'
};

export const BusinessCategoryLabels: Record<BusinessCategory, string> = {
  [BusinessCategory.ARTS_CRAFTS_PARTY_SUPPLIES]: 'Arts, Crafts & Party Supplies',
  [BusinessCategory.AUTO_TIRES_INDUSTRIAL]: 'Auto, Tires & Industrial',
  [BusinessCategory.BABY]: 'Baby',
  [BusinessCategory.BEAUTY_COSMETICS]: 'Beauty & Cosmetics',
  [BusinessCategory.BEDDING_LINENS]: 'Bedding & Linens',
  [BusinessCategory.CELL_PHONES_ACCESSORIES]: 'Cell Phones & Accessories',
  [BusinessCategory.CHAMBER]: 'Chamber',
  [BusinessCategory.CHILD_CARE_DAY_CARE]: 'Child Care & Day Care',
  [BusinessCategory.CLEANING_SUPPLIES]: 'Cleaning Supplies',
  [BusinessCategory.CLOTHING_SHOES_ACCESSORIES]: 'Clothing, Shoes & Accessories',
  [BusinessCategory.CONTENT_CREATION]: 'Content Creation',
  [BusinessCategory.CRAFT_KITS_DIY_PROJECTS]: 'Craft Kits & DIY Projects',
  [BusinessCategory.DIGITAL_PRODUCTS]: 'Digital Products',
  [BusinessCategory.DIRECTORY]: 'Directory',
  [BusinessCategory.EDUCATION]: 'Education',
  [BusinessCategory.ELECTRONICS_AUDIO]: 'Electronics & Audio',
  [BusinessCategory.EVENT_TICKETS_EXPERIENCES]: 'Event Tickets & Experiences',
  [BusinessCategory.EXERCISE_FITNESS]: 'Exercise & Fitness',
  [BusinessCategory.FILM_PRODUCTION]: 'Film & Production',
  [BusinessCategory.FINANCE_PAYMENTS]: 'Finance & Payments',
  [BusinessCategory.FINANCIAL_INSTITUTION]: 'Financial Institution',
  [BusinessCategory.FOOD_BEVERAGE]: 'Food & Beverage',
  [BusinessCategory.FURNITURE_APPLIANCES]: 'Furniture & Appliances',
  [BusinessCategory.GARDENING_TOOLS_SUPPLIES]: 'Gardening Tools & Supplies',
  [BusinessCategory.GIFTS_GREETING_CARDS]: 'Gifts & Greeting Cards',
  [BusinessCategory.GROCERY]: 'Grocery',
  [BusinessCategory.HEALTH_WELLNESS]: 'Health & Wellness',
  [BusinessCategory.HOME_IMPROVEMENTS_DECOR]: 'Home Improvements & Decor',
  [BusinessCategory.HOME_SECURITY_SMART_DEVICES]: 'Home Security & Smart Devices',
  [BusinessCategory.HOUSEHOLD_ESSENTIALS]: 'Household Essentials',
  [BusinessCategory.INFLUENCER]: 'Influencer',
  [BusinessCategory.JEWELRY_WATCHES]: 'Jewelry & Watches',
  [BusinessCategory.KITCHENWARE_COOKWARE]: 'Kitchenware & Cookware',
  [BusinessCategory.LUGGAGE_BAGS]: 'Luggage & Bags',
  [BusinessCategory.MEDICAL_HEALTHCARE]: 'Medical & Healthcare',
  [BusinessCategory.MERCHANT_SERVICES]: 'Merchant Services',
  [BusinessCategory.MISCELLANEOUS]: 'Miscellaneous',
  [BusinessCategory.MOBILE_APPS_SOFTWARE_LICENSES]: 'Mobile Apps & Software Licenses',
  [BusinessCategory.MUSIC_MOVIES_BOOKS]: 'Music, Movies & Books',
  [BusinessCategory.NONPROFIT]: 'Nonprofit',
  [BusinessCategory.OFFICE_FURNITURE]: 'Office Furniture',
  [BusinessCategory.OFFICE_SUPPLIES]: 'Office Supplies',
  [BusinessCategory.OUTDOOR_CAMPING_EQUIPMENT]: 'Outdoor & Camping Equipment',
  [BusinessCategory.PATIO_GARDEN]: 'Patio & Garden',
  [BusinessCategory.PERSONAL_CARE]: 'Personal Care',
  [BusinessCategory.PETS]: 'Pets',
  [BusinessCategory.PHARMACY_HEALTH_WELLNESS]: 'Pharmacy, Health & Wellness',
  [BusinessCategory.PROFESSIONAL_SERVICES]: 'Professional Services',
  [BusinessCategory.REAL_ESTATE]: 'Real Estate',
  [BusinessCategory.RELIGIOUS_SPIRITUAL]: 'Religious & Spiritual',
  [BusinessCategory.RESTAURANTS_BARS_LOUNGE]: 'Restaurants, Bars & Lounge',
  [BusinessCategory.SEASONAL_HOLIDAY_ITEMS]: 'Seasonal & Holiday Items',
  [BusinessCategory.SPORTS_OUTDOORS]: 'Sports & Outdoors',
  [BusinessCategory.STATIONERY_OFFICE_SUPPLIES]: 'Stationery & Office Supplies',
  [BusinessCategory.SUBSCRIPTION_BOXES]: 'Subscription Boxes',
  [BusinessCategory.TECHNOLOGY]: 'Technology',
  [BusinessCategory.TOOLS_HARDWARE]: 'Tools & Hardware',
  [BusinessCategory.TOYS_GAMES]: 'Toys & Games',
  [BusinessCategory.TRADE_ASSOCIATION]: 'Trade Association',
  [BusinessCategory.TRAVEL_TRANSPORTATION]: 'Travel & Transportation',
  [BusinessCategory.VINTAGE_COLLECTIBLES]: 'Vintage & Collectibles',
  [BusinessCategory.WINE_SPIRITS_LIQUOR]: 'Wine, Spirits & Liquor'
};