name: Deploy to Development

on:
  push:
    branches: [ dev, development ]
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for development
      run: npm run build
      env:
        NODE_ENV: development
        VITE_SUPABASE_URL: ${{ secrets.DEV_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.DEV_SUPABASE_ANON_KEY }}
        
    - name: Deploy to Netlify (Dev)
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=dist --site=${{ secrets.DEV_NETLIFY_SITE_ID }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        
    - name: Comment deployment URL
      uses: actions/github-script@v7
      if: github.event_name == 'push'
      with:
        script: |
          const deployUrl = `https://dev-blackowndemand.netlify.app`;
          console.log(`🚀 Development deployment: ${deployUrl}`);